# Generated by Django 5.2.3 on 2025-07-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_assignmentsubmission_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttask',
            name='is_completed',
        ),
    ]
