# Generated by Django 5.2.3 on 2025-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_assignmenttask_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
